/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import AccesoDatos.conexion;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.sql.ResultSet;
import java.util.Calendar;
import java.util.TimerTask;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Portege
 */
public class Acceso extends javax.swing.JFrame {
String tipoMov = "S";
ImageIcon imagenerror;
ImageIcon imagenok;
ImageIcon imagenabajo;
java.util.Calendar calendario; 
int dia, mes, año, hora, minutos, segundos; 

    /**
     * Creates new form Acceso
     */
    public Acceso() {
        initComponents();
        reloj();
    }
    
 Timer timer = new Timer (5000, new ActionListener () 
{ 
    public void actionPerformed(ActionEvent e) 
    { 
           estadoInicial();
          
     } 
}); 
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIcono = new javax.swing.JLabel();
        jtextrut = new javax.swing.JTextField();
        txtestado = new javax.swing.JTextField();
        Mensaje = new javax.swing.JLabel();
        labelreloj = new javax.swing.JLabel();
        Icono2 = new javax.swing.JLabel();
        LblPrincipal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/error.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 600));
        setMinimumSize(new java.awt.Dimension(1024, 600));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1024, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtextrut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextrutActionPerformed(evt);
            }
        });
        jtextrut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtextrutKeyPressed(evt);
            }
        });
        getContentPane().add(jtextrut, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 150, 30));

        txtestado.setText("E");
        getContentPane().add(txtestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 20, -1));
        getContentPane().add(Mensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, 40));

        labelreloj.setFont(new java.awt.Font("Arial", 1, 80)); // NOI18N
        labelreloj.setForeground(new java.awt.Color(0, 0, 81));
        labelreloj.setText("Reloj");
        getContentPane().add(labelreloj, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 481, 280));

        Icono2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/abajo.png"))); // NOI18N
        getContentPane().add(Icono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, -1, -1));

        LblPrincipal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        LblPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        LblPrincipal.setText("Acerque Cedula al lector");
        getContentPane().add(LblPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/fondo2.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1070, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void AnalizaMov(){
         ResultSet rs;
        int cantidad=0;
        String estado="NO";       
        String Autorizado="NO";
        tipoMov = txtestado.getText();
        rs = conexion.DatosMov(Integer.parseInt(jtextrut.getText()), "");
        int MovId;
        String ipequipo="123";
        int ID_PERSONA_APROBADA=0;
        String resp;        
try{
    
while(rs.next()) {
    
estado = rs.getString("ESTADO");
Autorizado = rs.getString("AUTORIZACION");
ID_PERSONA_APROBADA = Integer.parseInt(rs.getString("ID_PERSONA_APROBADA"));

        
cantidad = cantidad + 1;
 
   
}

if (tipoMov.equals("E"))
{
    if("FUERA DE PUERTO".equals(estado) && "APROBADO".equals(Autorizado)){
        
    resp = conexion.Procedimiento_1(1, ipequipo, ID_PERSONA_APROBADA);
    if (resp.equals("ok")){
    LblPrincipal.setText("ACCESO CORRECTO");
    Icono2.setIcon(imagenok);
    timer.start();

    }else{
       LblPrincipal.setText("NO ES POSIBLE VALIDAR EL ACCESO,ACERQUESE A PORTERIA");
       timer.start();
    }
   


}else{
 LblPrincipal.setText("ACCESO DENEGADO");
 Icono2.setIcon(imagenerror);
 
 
 
 timer.start();
}


}else{
    
     if("EN PUERTO".equals(estado)){
     
    resp = conexion.Procedimiento_1(2, ipequipo, ID_PERSONA_APROBADA);
    if (resp.equals("ok")){
    
       LblPrincipal.setText("GRACIAS POR SU VISITA");
      Icono2.setIcon(imagenok);
      timer.start();
    }else{
    LblPrincipal.setText("NO ES POSIBLE VALIDAR ,ACERQUESE A PORTERIA");
    Icono2.setIcon(imagenerror);
    timer.start();
    }
         
    
   
     }else{
            LblPrincipal.setText("NO ES POSIBLE VALIDAR EL ACCESO,ACERQUESE A PORTERIA");
       Icono2.setIcon(imagenerror);
       timer.start();
     }


}


        


}catch(Exception ex){
       JOptionPane.showMessageDialog(null, ex.getMessage(),"error",JOptionPane.ERROR_MESSAGE);
}

    
    }
    private void jtextrutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtextrutKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        
        AnalizaMov();
        }
    }//GEN-LAST:event_jtextrutKeyPressed

    
    public void estadoInicial(){
    Icono2.setIcon(imagenabajo);
    jtextrut.setText("");
    jtextrut.requestFocus();
     LblPrincipal.setText("Acerque cedula al lector");
    
    timer.stop();
    }
    
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

     String pathabajo = "abajo.png";  
URL url = this.getClass().getResource(pathabajo);  
imagenabajo = new ImageIcon(url);  

String pathok = "ok.png";  
URL url1 = this.getClass().getResource(pathok);  
imagenok = new ImageIcon(url1);  

String patherror = "error.png";  
URL url2 = this.getClass().getResource(patherror);  
imagenerror = new ImageIcon(url2);  



lblIcono.setIcon(imagenabajo);
Font myFont = new Font("Serif", Font.BOLD, 18);

Mensaje.setFont(myFont);
conexion.getConexion();
    }//GEN-LAST:event_formWindowActivated

    private void jtextrutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextrutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextrutActionPerformed

       private void reloj() { 
calendario = new java.util.GregorianCalendar(); 
segundos = calendario.get(Calendar.SECOND); 
javax.swing.Timer timer = new javax.swing.Timer(1000, new java.awt.event.ActionListener() { 
@ Override 
public void actionPerformed(java.awt.event.ActionEvent ae) { 
java.util.Date actual = new java.util.Date(); 
calendario.setTime(actual); 
dia = calendario.get(Calendar.DAY_OF_MONTH); 
mes = (calendario.get(Calendar.MONTH) + 1); 
año = calendario.get(Calendar.YEAR); 
hora = calendario.get(Calendar.HOUR_OF_DAY); 
minutos = calendario.get(Calendar.MINUTE); 
segundos = calendario.get(Calendar.SECOND); 
String hour = String.format("%02d : %02d : %02d", hora, minutos, segundos); 
String date = String.format("%02d / %02d / %02d", dia, mes, año); 
labelreloj.setText("<html><center>" + hour + "<br><h1>" + date+"</h1>"); 
   } 
}); 
timer.start(); 
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acceso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Icono2;
    private javax.swing.JLabel LblPrincipal;
    private javax.swing.JLabel Mensaje;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jtextrut;
    private javax.swing.JLabel labelreloj;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JTextField txtestado;
    // End of variables declaration//GEN-END:variables
}
